{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Acessos na página\",\"Catálogo livros\",\"Número de livros vendidos\",\"Vendas por semana\",\"Clientes\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "e1248801-785f-48cd-9cde-0aef38278c13",
        "fromColumn": "Data",
        "fromTable": "Número de livros vendidos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7b2c2a57-e55b-4083-ba6a-f1590b7f77ff"
      },
      {
        "name": "18018d21-2133-488f-8dd7-7aae5634201b",
        "fromColumn": "Data",
        "fromTable": "Acessos na página",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0f698695-af2a-45e7-9bcd-623a7418d265"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Acessos na página",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ff7c0c32-de6c-4782-81c8-dccae7d1a0de",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_0f698695-af2a-45e7-9bcd-623a7418d265"
                },
                "isDefault": true,
                "relationship": "18018d21-2133-488f-8dd7-7aae5634201b"
              }
            ]
          },
          {
            "name": "Acessos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c50bc7fc-7ee8-4168-8205-0b9bc0a9ed2f",
            "sourceColumn": "Acessos",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ca2db60f-dff6-49f4-95ac-19e6bcf6c97a",
        "partitions": [
          {
            "name": "Acessos na página",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"D:\\Users\\usuario\\Downloads\\dashboard-power-bi_visualizando-dados.xlsx\"), null, true),",
                "    #\"Acessos na página_Sheet\" = Fonte{[Item=\"Acessos na página\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Acessos na página_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Data\", type date}, {\"Acessos\", type number}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [Data] <> null and [Data] <> \"\"),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Acessos\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ff8b3906-c411-49b2-9db2-72db99b551ee",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "709004f6-64c4-4888-9613-6c06c5035128",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "425e2935-9ecb-4627-9b59-51b7393f8d1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5f1a6be9-5ce9-41a5-a01e-c3c777ed65d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "215128a4-13f4-438c-8f0a-e3ac41c48956",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "93aa75dd-533d-4aba-81ea-9395056420e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fde43fc1-d288-40f0-8690-4840095c8ba2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0306ca81-39c6-413f-85c3-8b6d27629bd8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "c22298f0-0cae-4f4a-9a61-09d438d0fc4d",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "97e5cc94-26a3-4f2d-ab03-5150e2454489",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "caf43951-336f-4719-8927-962099e17935",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "a2408434-92df-4d48-8286-9cc5afd04f6f",
                "ordinal": 3
              }
            ],
            "lineageTag": "cba08c73-498a-497f-8647-37f644c2ea9d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "d1a1b810-cf65-4521-b8d6-a0d68dec7928",
        "partitions": [
          {
            "name": "DateTableTemplate_ff8b3906-c411-49b2-9db2-72db99b551ee",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Catálogo livros",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Titulo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfb7ef0e-5721-485d-9e99-3ad93c6ca261",
            "sourceColumn": "Titulo",
            "summarizeBy": "none"
          },
          {
            "name": "Código",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "275506a4-3f0b-4791-ab9f-1b5a57240db5",
            "sourceColumn": "Código",
            "summarizeBy": "sum"
          },
          {
            "name": "Autor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "254b456a-d273-4fd6-ab4d-eb5a1e4bb4e8",
            "sourceColumn": "Autor",
            "summarizeBy": "none"
          },
          {
            "name": "Assunto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bc9ba3a-db17-4550-9fe4-85670bf5d09d",
            "sourceColumn": "Assunto",
            "summarizeBy": "none"
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "feeaf131-34b6-4319-b307-0d18639ae75b",
            "sourceColumn": "Valor",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "99d0c61d-f846-44ed-92fb-7133c6f11cd7",
        "partitions": [
          {
            "name": "Catálogo livros",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"D:\\Users\\usuario\\Downloads\\dashboard-power-bi_visualizando-dados.xlsx\"), null, true),",
                "    #\"Catálogo livros_Sheet\" = Fonte{[Item=\"Catálogo livros\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Catálogo livros_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Titulo\", type text}, {\"Código\", Int64.Type}, {\"Autor\", type text}, {\"Assunto\", type text}, {\"Valor\", type number}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [Titulo] <> null and [Titulo] <> \"\"),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Valor\", Currency.Type}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Número de livros vendidos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "16e47a6a-9dcd-472e-87ed-fdb4f3c2e53f",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_7b2c2a57-e55b-4083-ba6a-f1590b7f77ff"
                },
                "isDefault": true,
                "relationship": "e1248801-785f-48cd-9cde-0aef38278c13"
              }
            ]
          },
          {
            "name": "Número de livros vendidos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "29d528b6-618e-4b7a-8f37-6497095a2b7f",
            "sourceColumn": "Número de livros vendidos",
            "summarizeBy": "sum"
          },
          {
            "name": "Grupo ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f1eca8a8-48bc-4a41-8438-a81911cbe9f0",
            "sourceColumn": "Grupo ",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8e2dfa28-9d7a-4339-8166-536cafcf14c5",
        "partitions": [
          {
            "name": "Número de livros vendidos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"D:\\Users\\usuario\\Downloads\\dashboard-power-bi_visualizando-dados.xlsx\"), null, true),",
                "    #\"Número de livros vendidos_Sheet\" = Fonte{[Item=\"Número de livros vendidos\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Número de livros vendidos_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Data\", type date}, {\"Número de livros vendidos\", Int64.Type}, {\"Grupo \", Int64.Type}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [Data] <> null and [Data] <> \"\")",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7b2c2a57-e55b-4083-ba6a-f1590b7f77ff",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "802583a4-9094-486c-b5b1-9320f9493cd0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "23966c72-6474-4594-a79f-33651a5498f8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6bde634d-848c-4338-9c17-cb7cb3d96422",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f2587adc-a13e-425a-a3a5-fffcbe6f3b10",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5c0f8991-9419-4041-8086-bff8ae41d8a7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c31b99e3-66c3-4d0b-9172-9aa026af5ecf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "43d9b008-d2fa-4a8d-bf44-5bb2bc06cdb4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "d1ae2b5d-633e-451b-bcae-a75705e1be50",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "418ab664-9876-483e-91da-3f734ca6357b",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "571cde9f-a898-44b9-a0f4-823ad5381e0e",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "22fc5229-afe8-45e5-81ee-20d2b7522a7d",
                "ordinal": 3
              }
            ],
            "lineageTag": "672cab11-25ba-40eb-a45e-1e128ec26012"
          }
        ],
        "isHidden": true,
        "lineageTag": "3bb84ba4-6df1-412a-907b-8d047862e343",
        "partitions": [
          {
            "name": "LocalDateTable_7b2c2a57-e55b-4083-ba6a-f1590b7f77ff",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Número de livros vendidos'[Data])), 1, 1), Date(Year(MAX('Número de livros vendidos'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Vendas por semana",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Semanas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d6fd86f-2bf4-4ab5-983a-0e5b2dc119f5",
            "sourceColumn": "Semanas",
            "summarizeBy": "sum"
          },
          {
            "name": "Vendas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2b61a3b-e680-4346-97a1-31ae9abc4676",
            "sourceColumn": "Vendas",
            "summarizeBy": "sum"
          },
          {
            "name": "Meta de vendas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e41bfb5a-0760-4b76-9bfa-572312cae609",
            "sourceColumn": "Meta de vendas",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "fe549cd2-5f66-4f5f-9733-4669b282b610",
        "partitions": [
          {
            "name": "Vendas por semana",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"D:\\Users\\usuario\\Downloads\\dashboard-power-bi_visualizando-dados.xlsx\"), null, true),",
                "    #\"Vendas por semana_Sheet\" = Fonte{[Item=\"Vendas por semana\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Vendas por semana_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Semanas\", Int64.Type}, {\"Vendas\", Int64.Type}, {\"Meta de vendas\", Int64.Type}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [Semanas] <> null and [Semanas] <> \"\")",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0f698695-af2a-45e7-9bcd-623a7418d265",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3b6c6fa7-6696-43c0-affc-67d6dabe0d1e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7172d168-9952-4aab-9a3e-941be1b9fa35",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "263dc9b8-37c8-4e52-8474-d327956c1375",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dcfe6339-7255-47ea-b61a-453d5eadf938",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3b984cc5-2e21-49cb-bfc2-147a759d0125",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "777f70da-bd1e-4a80-93cd-a4995da473bf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4021c5b1-559d-4c86-a403-f71435f89b83",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "37cf7c22-f17c-41ea-ba3b-8f5e59e2ade3",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "99f017fb-f5e4-475e-8eb0-060daf20827a",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "0f617691-c3bd-485b-8fc0-448a3dad0949",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "78ae482a-4cee-46ff-92f3-bdf5ef9bd958",
                "ordinal": 3
              }
            ],
            "lineageTag": "ba14030c-46ae-4064-b708-64b7cd3c39a9"
          }
        ],
        "isHidden": true,
        "lineageTag": "e6d93562-0695-4aa3-9065-ba83bf164709",
        "partitions": [
          {
            "name": "LocalDateTable_0f698695-af2a-45e7-9bcd-623a7418d265",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Acessos na página'[Data])), 1, 1), Date(Year(MAX('Acessos na página'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Clientes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "797fc651-9ed3-4ca4-8a25-ee8117bd3e34",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6726a88e-e3e4-4ded-a1ef-7411aa61ac44",
            "sourceColumn": "Idade",
            "summarizeBy": "sum"
          },
          {
            "name": "Gênero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49cc0732-e3b5-46cc-b74e-1ec2222b30e9",
            "sourceColumn": "Gênero",
            "summarizeBy": "none"
          },
          {
            "name": "Profissão",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20336d76-5fef-45ea-8571-2b418413c861",
            "sourceColumn": "Profissão",
            "summarizeBy": "none"
          },
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "5bbe4b8a-2b16-4f7c-b68b-9390afc22bd2",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0da0f79d-29b8-4d98-ae46-7916c1018930",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66398974-79a9-4a32-bbee-2b76eccd5633",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3433ba74-d2f5-4b69-830b-6fa8058a3e0f",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Assinatura ativa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "980b3180-d5d3-4c89-86e9-296d641728e5",
            "sourceColumn": "Assinatura ativa",
            "summarizeBy": "none"
          },
          {
            "name": "Contato Preferido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e34e670-bbbd-4ea0-8ff6-f976e6cf36c8",
            "sourceColumn": "Contato Preferido",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "62e168ce-f942-4c35-b211-e0fb6b4b4aac",
        "partitions": [
          {
            "name": "Clientes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"D:\\Users\\usuario\\Downloads\\dashboard-power-bi_visualizando-dados.xlsx\"), null, true),",
                "    Clientes_Sheet = Fonte{[Item=\"Clientes\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Clientes_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Nome\", type text}, {\"Idade\", Int64.Type}, {\"Gênero\", type text}, {\"Profissão\", type text}, {\"Cidade\", type text}, {\"Estado\", type text}, {\"Latitude\", type text}, {\"Longitude\", type text}, {\"Assinatura ativa\", type text}, {\"Contato Preferido\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}